### ISSUE TITLE
2022.06.26 회의 백엔드 요청사항

### ISSUE THREAD

**Issue by yoon6763** [KNU-NetworkSecurityLab/lab-server#17]
1. Response 값 JSON으로 통일

회원가입 성공 Response의 경우 SignUp Success라는 문자열 형태로 옵니다
{
“message” : “SignUp Success”
}

위와 같이 Response는 JSON 형식으로 통일하는게 좋을것 같아요

2. Message / msg 혼용
일부 항목에서는 msg가, 일부에서는 message가 쓰이고 있음
msg 혹은 message로 통일하는게 좋을 것 같아요

4. 서버 시간이 현시각이랑 좀 차이 나는거 같던데 UTC 인가요?
혹시 한국 시간으로 변경 가능한지… 안되도 크게 상관은 없어요

5. 혹시 기능 추가 될때마다 카톡/디코 남겨주실 수 있는지
로그인기능, 회원가입 기능, 도서기능 등등
백엔드에서 먼저 구축되고 앱에서 백엔드랑 통신(구현)
백엔드 기능이 업데이트 됬는지 안됬는지 저한테 알림 오는게 없어서
혹시 기능 업데이트 되면 디코나 카톡으로 메시지 한줄 보내주실 수 있을까요?

**Comment by kmg733** [comment]
- [x] Response 값 JSON으로 통일
- [x] 기존에 message 와 msg 혼용 하던 것 msg로 통일
- [x] 서버시간 KTC로 바꾸기

요청사항 서버 적용 완료 했음

요청사항 적용하면서 각 API 마다 수정 사항 생겼으니, 테스트 할 때 노션 API Docs 참고하면서 해
그리고 앞으로 수정 사항 생기면 DM이나 카톡으로 보낼께~

**Comment by yoon6763** [comment]
감사합니당
